SshriyaPieShop/Controllers/PieController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using SshriyaPieShop.Models;
using System.Security.Claims;

namespace SshriyaPieShop.Controllers
{
    public class PieController : Controller
    {
        private readonly IPieRepository _pieRepostiory;
        private readonly IMapper mapper;
        
        private readonly ICategoryRepository categoryRepostiory;
        private readonly IHttpContextAccessor httpContextAccessor;
        private readonly IConfiguration confriguration;
        string baseaddress;
        
        public PieController(IPieRepository pieRepostior, IMapper mapper, IHttpContextAccessor httpContext, IConfiguration confriguration, ICategoryRepository categoryRepostiory)
        {
            this._pieRepostiory = pieRepostior;
            this.mapper = mapper;
            this.httpContextAccessor = httpContext;
            this.categoryRepostiory = categoryRepostiory;
            baseaddress = confriguration.GetValue<string>("BaseAddress");
        }
        public async Task<ViewResult> List(int categoryId )
        {
            /*var user = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Name);
            Console.WriteLine(user);*/
            

            if (categoryId > 0)
            {
                IEnumerable<Pie> pies = new List<Pie>();
                using (var httpClient = new HttpClient())
                {
                   
                    using (var response = await httpClient.GetAsync("https://localhost:7070/Api/Pie/PiesbyCategoryId?id=" + categoryId))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        pies = JsonConvert.DeserializeObject<IEnumerable<Pie>>(apiResponse);//convert json to student array
                    }
                }
                //pies = _pieRepostiory.AllPies.Where(pie => pie.CategoryId == categoryId);
                return View(pies);
            }
            else
            {
                IEnumerable<Pie> pies = new List<Pie>();
                using (var httpClient = new HttpClient())
                 {
                     using (var response = await httpClient.GetAsync("https://localhost:7070/Api/Pie/GetAllPies"))
                     {
                         string apiResponse = await response.Content.ReadAsStringAsync();
                         pies = JsonConvert.DeserializeObject<IEnumerable<Pie>>(apiResponse);//convert json to student array
                     }
                 }
                return View(pies);
            }
            
        }


        public async Task<ViewResult> ListMini()
        {
            IEnumerable<Pie> pies = new List<Pie>();
            // var pie = _pieRepostiory.AllPies;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:7070/Api/Pie/GetAllPies"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    pies = JsonConvert.DeserializeObject<IEnumerable<Pie>>(apiResponse);//convert json to student array
                }
            }
            var piemini = mapper.Map<PieMini[]>(pies);
            Console.WriteLine(piemini);
            return View(piemini);
        }




        public async Task<ViewResult> Details(int id)
        {
            IEnumerable<Pie> pies = new List<Pie>();
            // var pie = _pieRepostiory.AllPies;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:7070/Api/Pie/DetailsofPie?id="+id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    pies = JsonConvert.DeserializeObject<IEnumerable<Pie>>(apiResponse);//convert json to student array
                }
            }
            var pie  = pies.FirstOrDefault(pie => pie.PieId == id);
            
            return View(pie);

        }

        public async Task<ViewResult> PiesOfTheWeek()
        {
          
            IEnumerable<Pie> pies = new List<Pie>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:7070/Api/Pie/PiesOfTheWeek"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    pies = JsonConvert.DeserializeObject<IEnumerable<Pie>>(apiResponse);//convert json to student array
                }
            }
            return View(pies);
            //Because return type is task that's why recieve is result 

        }
        public IActionResult FindPie(string name)
        {
            IEnumerable<Pie> pie = new List<Pie>();

            var pies = _pieRepostiory.AllPies.Where(pies => pies.Name.ToUpper().Contains(name.ToUpper()));
            return View(pies);
            //Because return type is task that's why recieve is result 

        }
        [Authorize]
        public ViewResult Create()
        {
           var categories =  categoryRepostiory.AllCategories;

            var categoriesItems = new List<SelectListItem>();
            foreach (var category in categories)
            {
                categoriesItems.Add(new SelectListItem { Text = category.CategoryName, Value = category.CategoryId.ToString() });
            }

            // var pie = new Pie();
            ViewBag.Categories = categoriesItems;
            return View();
        }


        public async Task<IActionResult> CreatePie(Pie pie)
        {
            IEnumerable<Pie> pies = new List<Pie>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.PostAsJsonAsync("https://localhost:7070/Api/Pie/InsertPie", pie))
                {
                    /*string apiResponse = await response.Content.ReadAsStringAsync();
                    pies = JsonConvert.DeserializeObject<IEnumerable<Pie>>(apiResponse);//convert json to student array*/
                    return RedirectToAction("PiesOfTheWeek");
                }
            }
            return RedirectToAction("PiesOfTheWeek");

            // var pies = _pieRepostiory.CreatePie(pie);
            //return View(pies);
        }
        public async Task<IActionResult> DeletePie(int pieId)
        {
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.DeleteAsync("https://localhost:7070/Api/Pie/RemovePie?pieId=" + pieId))
                {
                      string apiResponse = await response.Content.ReadAsStringAsync();
                    
                }
            }
            return RedirectToAction("PiesOfTheWeek");
        }
       

        public async Task<ViewResult> Edit(int id)
        {

            IEnumerable<Pie> pies = new List<Pie>();
            
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:7070/Api/Pie/DetailsofPie?id=" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    pies = JsonConvert.DeserializeObject<IEnumerable<Pie>>(apiResponse);//convert json to student array
                }
            }
            var pie = pies.FirstOrDefault(pie => pie.PieId == id);

            
            //var pies = _pieRepostiory.AllPies.FirstOrDefault(pie => pie.PieId == id);
            var categories = categoryRepostiory.AllCategories;

            var categoriesItems = new List<SelectListItem>();
            foreach (var category in categories)
            {
                categoriesItems.Add(new SelectListItem { Text = category.CategoryName, Value = category.CategoryId.ToString() });
            }
            ViewBag.Categories = categoriesItems;
            return View(pie);
          

        }

        
        public async Task<IActionResult> UpdatePie(Pie pie)
        {
            IEnumerable<Pie> pies = new List<Pie>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.PutAsJsonAsync("https://localhost:7070/Api/Pie/UpdatePie", pie))
                {
                    return RedirectToAction("PiesOfTheWeek");
                }
            }
            return RedirectToAction("PiesOfTheWeek");


        }



/*
        [Authorize]
        public async Task<IActionResult> AddToCart(int id)
        {
            IEnumerable<Pie> pies = new List<Pie>();
        
            // var pie = _pieRepostiory.AllPies;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:7070/Api/Pie/GetAllPies"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    pies = JsonConvert.DeserializeObject<IEnumerable<Pie>>(apiResponse);//convert json to student array
                }
            }
            var pie = pies.FirstOrDefault(pie => pie.PieId == id);
            string cartid = this.httpContextAccessor.HttpContext.User.Identity.Name;
            
           var order1 = _pieRepostiory.AllOrders.SingleOrDefault(p => (p.CartId == cartid) && (p.PieId == id));
            if (order1 == null)
            {
                Order order = new Order();
                
                order.PieId = pie.PieId;
                order.PiePrice = pie.Price;
                order.Quantity = 1;
                order.PieName = pie.Name;
                order.CartId = cartid;
                order.Bill = (int)(order.Quantity * order.PiePrice);
                var result = order;

SshriyaPieShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MYPieShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SshriyaPieShop.styles.css" asp-append-version="true" />
     <style>
    
</style>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="PIE" asp-action="list">Shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="pie" asp-action="PiesOfTheWeek">Pies</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="pie" asp-action="ListMini">ListMini</a>
                        </li>
                       
                            <li class="dropdown">
                              <button class="dropbtn">Filter</button>
                              <div class="dropdown-content">
                               <a class="nav-link" asp-controller="pie" asp-action="Ascending">Ascending</a>
                              <a class="nav-link" asp-controller="pie" asp-action="Descending">Descending</a>
                              
                              </div>
                            </li>
                       
                        
                        @await Component.InvokeAsync("CategoryMenu")
                       

                        <li class="nav-item">
                             <partial name = "_LoginPartial"/>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="pie" asp-action="Create">Create</a>
                        </li>
                         <li class="nav-item">
                            <a asp-controller="shoppingcart" asp-action="Index"> <p class="lead">
                    <img class="img-responsive" alt="Pie Shop" src="~/Image/cart.png" height="40" width="40">
                    
                </p>  </a>
                        </li>
                         <form class="d-flex" asp-controller="Pie" asp-action="FindPie" method="get">
                         <input class="form-control me-sm-2" type="text" placeholder="Search" name="name">
                        <button class="btn btn-primary" type="submit">Search</button>
                      </form>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
  
        <div class="container">
        <div class="row">
            <h3 >MY-PIE-SHOP.</h3>
            <div>
                <blockquote class="blockquote mb-0">
                 <p>“We must have a pie. Stress cannot exist in the presence of a pie.”</p>
      
                 </blockquote></div>
            <div class="col-md-2">
                <p class="lead">
                    <img class="img-responsive" alt="Pie Shop" src="~/Image/logo.jpg" height="100" width="100">

                </p>
           </div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div></div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SshriyaPieShop/Views/Shared/_PiePartial.cshtml
@model IEnumerable<Pie>
<div>
    <div>

         @foreach (var pie in Model)
      {
        <div class="gallery">
          <a target="_blank" href= "@pie.ImageThumbnailUrl">
            <img src="@pie.ImageThumbnailUrl" alt="Cinque Terre" width="600" height="400">
          </a>
          
          <div> <a asp-action="Details" asp-route-id="@pie.PieId">@pie.Name</a></div>
          <div> Rs: @pie.Price</div>

          <div class="desc">@pie.ShortDescription</div>
          @* <div class = button2><a asp-controller="Pie" asp-action="AddToCart" asp-route-id="@pie.PieId">AddToCart</a></div>*@
          @if(pie.InStock){
              <div class="addToCart">
                <p class="button">
                    <a class="btn btn-primary" 
                       asp-controller="ShoppingCart" 
                       asp-action="AddToShoppingCart"
                       asp-route-pieId="@pie.PieId">Add to cart</a>
                </p>
            </div>
          }
         @if(!pie.InStock )
          {
              <div class="addToCart">
                <p class="button">
                    <a class="btn btn-danger" 
                       
                       asp-action="#"
                       asp-route-pieId="@pie.PieId">Out Of Stock</a>
                </p>
            </div>
          }
           @*<div class="addToCart">
                <p class="button">
                    <a class="btn btn-primary" 
                       asp-controller="ShoppingCart" 
                       asp-action="wishlist"
                       asp-route-pieId="@pie.PieId">Wishlist</a>
                </p>
            </div>*@
           
                     <div> <p class="button">
                    <a class="btn btn-danger" 
                       asp-controller="pie" asp-action = "DeletePie"  asp-route-pieId="@pie.PieId"> Delete
                       </a>
             </div>
        </div>
       
      }
    </div>
    